name: Build and deploy Gradle app to Azure Web App - princesstown

on:
  push:
    branches:
      - feature/Develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Delete previous build artifacts
        run: rm -rf build/libs/*

      - uses: actions/checkout@v2
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: gradle-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: https://princesstown.azurewebsites.net # Update this with your actual Azure Web App URL

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: gradle-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'princesstown' # Update this with your Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E2B3A8EC88464C2CA3BD8869B9F788CA }}
          package: 'princesstown-0.0.1-SNAPSHOT.jar'